### ISSUE TITLE
Error when requesting `iamr` IAM Roles

### ISSUE THREAD

**Issue by kitforbes** [dtan4/dockerfile-terraforming#30]
### Description
From executing the blow command on WIndows 10, I get the error `uninitialized class variable`. I tried a number of other `iam` specific calls, and all seem to be okay.

And I probably shouldn't have raised this in this repo... sorry about that.

### Command
```batch
docker run --rm --name terraforming ^
    -e AWS_ACCESS_KEY_ID=%AWS_ACCESS_KEY_ID% ^
    -e AWS_SECRET_ACCESS_KEY=%AWS_SECRET_ACCESS_KEY% ^
    -e AWS_REGION=eu-west-1 ^
    quay.io/dtan4/terraforming ^
    terraforming iamr
```

### Exception
```
/usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:21:in `unescape': uninitialized class variable @@accept_charset in #<Class:CGI> (NameError)
Did you mean?  @@accept_charset
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:21:in `prettify_policy'
        from (erb):6:in `block in apply_template'
        from (erb):1:in `each'
        from (erb):1:in `apply_template'
        from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
        from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:4:in `apply_template'
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/iam_role.rb:19:in `tf'
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/iam_role.rb:7:in `tf'
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:240:in `tf'
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:227:in `execute'
        from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:104:in `iamr'
        from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /usr/local/bundle/gems/terraforming-0.13.2/bin/terraforming:5:in `<top (required)>'
        from /usr/local/bundle/bin/terraforming:17:in `load'
        from /usr/local/bundle/bin/terraforming:17:in `<main>'
```

**Comment by Heiko-san** [comment]
Hi,

I have the very same problem using the docker container on a linux platform.
Are there any hints on how to solve?
Calling it with "vpc" for example seems to work but anything I tried with "iam" (iamr, iamp,...) produces the error.

**Comment by mabushey** [comment]
I think this has been fixed, I get terrraform output from this docker container w/iamr and iamp. I'm using docker 18.03.0-ce on Ubuntu.
