### ISSUE TITLE
AuthFailure when using terraforming in Docker

### ISSUE THREAD

**Issue by lyoungblood** [dtan4/dockerfile-terraforming#31]
Calling terraforming in docker fails, but the same exact credentials in Mac OS X work correctly:

$ docker run --rm --name terraforming -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=us-east-1 quay.io/dtan4/terraforming:latest terraforming ec2
/usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': AWS was not able to validate the provided access credentials (Aws::EC2::Errors::AuthFailure)
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.9/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/ec2.rb:108:in `instances'
	from (erb):1:in `apply_template'
	from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:4:in `apply_template'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/ec2.rb:19:in `tf'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/ec2.rb:7:in `tf'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:240:in `tf'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:227:in `execute'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:44:in `ec2'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/terraforming-0.13.2/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bundle/bin/terraforming:17:in `load'
	from /usr/local/bundle/bin/terraforming:17:in `<main>'
f45c89b04cf3:~ lukey$ terraforming ec2
resource "aws_instance" "master-us-east-1c-masters-k8s-aws-stacks-space" {
    ami                         = "ami-4bb3e05c"
...

**Comment by lyoungblood** [comment]
Tested using commit ad47fa76f2 (terraforming 0.13.1) and it works fine.  Seems to be a regression with the upgrade to 0.13.2.
